### ISSUE TITLE
Sending from localhost

### ISSUE THREAD

**Issue by andrecasal** [resendlabs/resend-node#109]
I'm having this error in both staging and locally:

```sh
Error: Unexpected Server Error
    at handleDataRequestRR (/Users/andrecasal/Developer/Apps/andrecasal.com/node_modules/@remix-run/server-runtime/dist/server.js:11:3342)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at requestHandler (/Users/andrecasal/Developer/Apps/andrecasal.com/node_modules/@remix-run/server-runtime/dist/server.js:11:1320)
    at /Users/andrecasal/Developer/Apps/andrecasal.com/node_modules/@remix-run/express/dist/server.js:11:420
```

This doesn't contain any useful information as to why
```tsx
return await resend.emails.send({
	from: 'my@email.com',
	...email,
})
```
is failing.

My guess is that neither localhost or staging are verified domains. **Edit**: Actually, probably not, as one doesn't necessarily need to send emails from the same domain we verified.

How would one go about debugging this? If it's a domain verification issue, how would one allow localhost and staging?

**Comment by andrecasal** [comment]
I was sending `from: 'hello@mydomain.com'` so people can reply back to me. Changing it to `from: 'hello@transactional.mydomain.com'` (my verified domain) and adding a `reply_to: hello@mydomain.com` fixed it.
